version: "3"

services:

  color-selector-api:
    image: color-selector-api:latest
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/color-selector"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "password"

  postgres:
    image: postgres
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "color-selector"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"