version: "3"

services:

  color-selector-api:
    build: .
    # image: color-selector-api:latest
    ports:
      - 5005:5005
      - 8000:8000
    volumes:
      - "~/.sbt:/root/.sbt"
      - "~/Library/Caches/Coursier:/root/.cache/coursier" # MacOS Coursier cache
      #      - "~/.cache/coursier:/root/.cache/coursier" # Linux Coursier cache
      #      - "~/AppData/Local/Coursier/Cache:/root/.cache/coursier" # Windows Coursier cache
      - ".:/opt/color-selector-api"
      - "/opt/color-selector-api/target"
      - "/opt/color-selector-api/project/target"
      - "/root/.sbt/1.0/plugins"
