FROM openjdk:11-jre-slim

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

WORKDIR /opt/color-selector-api

ADD color-selector-api-*.tgz .

EXPOSE 8000

CMD [ "/opt/color-selector-api/bin/color-selector-api" ]
